# Generated by Django 5.1.2 on 2024-10-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category/', verbose_name='Kategoriya Rasmi'),
            preserve_default=False,
        ),
    ]
