# Generated by Django 5.1.2 on 2024-10-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mahsulot Narxi'),
        ),
    ]
