# Generated by Django 5.1.2 on 2024-10-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ijtimoiy Tarmoq nomi'),
        ),
    ]
