# Generated by Django 5.1.2 on 2024-10-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_social_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
