# Generated by Django 5.1.2 on 2024-10-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mahsulot Hajmi'),
        ),
    ]
