# Generated by Django 5.1.2 on 2024-10-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_product_price_type_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_shoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mahsulot (Oyoq Kiyim) Hajmi'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mahsulot (Kiyim) Hajmi'),
        ),
    ]
