# Generated by Django 5.1.2 on 2024-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='1', max_length=14),
            preserve_default=False,
        ),
    ]
