# Generated by Django 5.1.2 on 2024-10-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_order_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Salon Kategoriya Nomi')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beauty_Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=222, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price_type', models.CharField(blank=True, choices=[('uzs', 'UZS'), ('usd', 'USD')], max_length=3, null=True, verbose_name='Xizmat Narxi Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='beauty_salon/', verbose_name='Xizmat Rasmi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.beauty_category', verbose_name='Xizmat Kategoriyasi')),
            ],
        ),
    ]
