# Generated by Django 5.1.2 on 2024-10-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_beauty_category_beauty_salon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beauty_Category',
            new_name='BeautyCategory',
        ),
        migrations.RenameModel(
            old_name='Beauty_Salon',
            new_name='BeautySalon',
        ),
    ]
