# Generated by Django 5.1.2 on 2024-10-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_rename_beauty_category_beautycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautysalon',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='beauty_salon/videos/', verbose_name='Xizmat Videosi'),
        ),
        migrations.AlterField(
            model_name='beautysalon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.beautycategory', verbose_name='Xizmat Kategoriyasi, Majburiy'),
        ),
        migrations.AlterField(
            model_name='beautysalon',
            name='name',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name="Xizmat Nomi, Agar kerak bo'lsa"),
        ),
        migrations.AlterField(
            model_name='beautysalon',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Xizmat Narxi, Agar kerak bo'lsa"),
        ),
    ]
