# Generated by Django 5.1.2 on 2024-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_product_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[("so'm", "SO'M"), ('$', '$')], max_length=4, verbose_name='Mahsulot Narxi Turi'),
        ),
    ]
