# Generated by Django 5.1.2 on 2024-12-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_product_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/multiple/', verbose_name="Mahsulot Qo'shimcha Rasmi")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apps.product', verbose_name='Mahsulot Rasmi')),
            ],
        ),
    ]
