# Generated by Django 5.1.2 on 2024-12-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name="Mahsulot Qo'shimcha Rasmi"),
        ),
    ]
